# Generated by Django 4.2.2 on 2023-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
