# Generated by Django 4.2.3 on 2023-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_job_character_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='agility_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='dexterity_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='intelligence_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='mind_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='strength_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='vitality_mod',
            field=models.FloatField(choices=[(2.0, 'A'), (1.8, 'B'), (1.6, 'C'), (1.4, 'D'), (1.2, 'E'), (1.0, 'F')]),
        ),
    ]
