# Generated by Django 4.2.3 on 2023-08-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_job_agility_mod_alter_job_dexterity_mod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobs_can_equip', models.ManyToManyField(to='characters.job')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('magic_mod', models.IntegerField(default=0)),
                ('accuracy_mod', models.IntegerField(default=0)),
                ('evasion_mod', models.IntegerField(default=0)),
                ('speed_mod', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobs_can_equip', models.ManyToManyField(to='characters.job')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('magic_mod', models.IntegerField(default=0)),
                ('accuracy_mod', models.IntegerField(default=0)),
                ('evasion_mod', models.IntegerField(default=0)),
                ('speed_mod', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('armor_slot', models.CharField(choices=[('Head', 'Head'), ('Body', 'Body'), ('Hands', 'Hands'), ('Feet', 'Feet')], max_length=5)),
                ('armor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.armortype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_body_equipped', to='characters.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='feet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_feet_equipped', to='characters.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='hands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_hands_equipped', to='characters.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_head_equipped', to='characters.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_weapon_equipped', to='characters.weapon'),
        ),
    ]
